### ISSUE TITLE
Scaling on a 4K Screen

### ISSUE THREAD

**Issue by ghost** [solus-project/lightdm-budgie-greeter#1]
First of all many thanks for all the hard work with Budgie, amazing piece of code.

It is great to see that LightDM will be modified to fit Budgie. It would be fantastic if there was a way to set up the theme and wallpaper for the greeter - always annoying if it looks completely different from the desktop.

Just wanted to report that in a 4K screen Budgie scales wonderfully without a single click. The GRUB selection screen and the greeter are, however, incredibly small. While grub is not part of Solus (though it can be fixed by setting a big terminal font - instructions are on Arch wiki) it would be fantastic if the greeter scaled automatically the same way the main desktop does.

Many thanks in advance!

**Comment by ikeydoherty** [comment]
Yeah scaling should definitely be a priority for the greeter. It won't be properly implemented until after Solus 1.2.1, but agreed, it should be in accordance with the rest of Budgie :)

**Comment by ghost** [comment]
Fantastic, looking forward to the implementation.

**Comment by CoalaJoe** [comment]
I really need that!

**Comment by vrakesh** [comment]
Any update on the issue? I do experience this still

**Comment by ikeydoherty** [comment]
Issue? This is a concept repo and contains no code - so there is nothing in this project that affects you.
